### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tableDnDConfig' of null

### ISSUE THREAD

**Issue by relipse** [isocra/TableDnD#39]
Each time I reorder a row, I get this error

**Comment by brendon** [comment]
Hi Dennis, I was wondering if you had any ideas on why this might be happening? Did you get a chance to check out the jsfiddle? :) Happy New Year by the way!

**Comment by isocra** [comment]
Hi Brendon,

Happy New Year to you too! 

Thanks for the jsFiddle. I had to change the external resource url to tablednd.js (as it said the mime type was wrong), but then I was able to see the problem. The `processMouseup` method was being called when there wasn't a current table and the check for this was after it checked for the config (doh!).

I've swapped the sections round and it seems to work. I've currently done this in a branch [feature/issue-39-fix-null-tableDnDConfig](https://github.com/isocra/TableDnD/tree/feature/issue-39-fix-null-tableDnDConfig) and I've got an updated jsFiddle to test it: http://jsfiddle.net/DenisHo/tb385req/4/.

Could you have a play and see if it works with this version? If so I'll merge it back into master.

Thanks
Denis

**Comment by brendon** [comment]
Hi Denis, thanks for your reply!

I've had a play with this but unfortunately it doesn't work. While I'm not able to test for the original error, now the mouse won't let go of the item being dragged. Basically once you click and start dragging, even letting go of the mouse button won't stop the item following where the mouse pointer is. Seems logical since you've changed something in the mouseUp :)

I hope that helps. I reverted the change just to check, and the behaviour returned to normal (in terms of the item staying put when the mouse was released) :)

Let me know if you need more information :)

**Comment by isocra** [comment]
Doh! Stupid mistake on my part, I was checking `droppedRow` before I initialised it. Could you have another check now: http://jsfiddle.net/DenisHo/tb385req/6/.

Thanks 
Denis

**Comment by brendon** [comment]
Hi Denis, that works great now! Thanks for fixing it :D

**Comment by isocra** [comment]
Great, I'll merge this branch back in to Master

**Comment by sebastiansulinski** [comment]
Hi Denis - did you actually push this update to the repository?
I've just installed it via bower directly from repo and still get the same error.

**Comment by andreaswalter** [comment]
Same error for me. Also installed it via bower.

**Comment by brendon** [comment]
It seems to have been merged here:

https://github.com/isocra/TableDnD/commit/796260929c1f00079520c2454bb83b31cfc72e48

I'd say the bower version is out of date. I don't see any reference to an updated version since then in the commits. This is the file to use:

https://github.com/isocra/TableDnD/blob/master/js/jquery.tablednd.js
