### ISSUE TITLE
"nodrop" as a function

### ISSUE THREAD

**Issue by smereddy** [isocra/TableDnD#96]
Thank you for all the hard work you guys have put in this project.  

I am trying to using tableDnD to sort a priority queue in which certain positions are fixed and other draggable rows cannot take its place. "noDrop" is a good implementation but there are certain issues with it.

From the documentation: 

1 | One |  
2 | Two |  
3 | Three (Can't drop on this row) |  
4 | Four (Can't drop on this row) |  
5 | Five |  
6 | Six (Can't drag this row) |  
7 | Seven |  

if I move 5 -> 2, then 2 will take 3s place.

1 | One |  
5 | Five |  
2 | Two |  
3 | Three (Can't drop on this row) |  
4 | Four (Can't drop on this row) |  
6 | Six (Can't drag this row) |  
7 | Seven |  

Which in turn beats the purpose of having a not dropable row because now I can move 5-> 2.

I am trying to create a priority table where positions are fixed, so when we move 5->2, 2 will move to next moveable position: example,

1 | One |  
5 | Five |  
3 | Three (Can't drop on this row) |  
4 | Four (Can't drop on this row) |  
2 | Two |  
6 | Six (Can't drag this row) |  
7 | Seven |  

Is there a fix for this?

**Comment by isocra** [comment]
Hi @smereddy, have you tried using `onAllowDrop`? You can specify a function which takes the dragged row and the target row and return true or false. 

However, this might not do what you want because you really want to insert it after a _different_ row to the one it's actually dropped on and that's not something that's supported at the moment. If that's what you need, I'm afraid you'd have to fork this repo. You could then change the code around line 412 and maybe add a new config function something like `onDetermineDropRow(draggedRow, targetRow) => row | null`. 

I hope that helps!
